config/routes.rb
MatrixPlots::Application.routes.draw do

root to: 'plots#index'

resources :plots

end

app/models/plot.rb
class Plot < ActiveRecord::Base
  attr_accessible :story, :title
  validates :story, :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
	def index
		@plots = Plot.all
	end
	
	def new
		@plot = Plot.new
	end
	
	def create
		@plot = Plot.new(params[:plot])
		if @plot.save
		  flash[:notice] = "added..."
		  redirect_to plots_path
	  else
	    flash[:alert] = "We have a problem."
	    render "new"
	  end
	end
	
	def show
		@plot = Plot.find(params[:id])
	end
	
	def edit
	  @plot = Plot.find(params[:id])
	end
	
	def update
		@plot = Plot.find(params[:id])
		@plot.update_attributes(params[:plot])
		redirect_to plot_path(@plot)
		
	end
	
	def destroy
	  @plot = Plot.find(params[:id])
	  @plot.destroy
	  redirect_to plots_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Next Matrix Plots</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<h3>By<a href="http://www.twitter.com/dmwoodall">Dave Woodall</a>at<a href="http://www.codeacademy.org">Code Academy</a>using<a href="http://www.rubyonrails.org">Ruby on Rails</a>.</h3>
</body>
</html>

app/views/plots/_form.html.erb
<%= link_to "take the blue pill", plots_url, class: "blueButton" %>
<%= form_for @plot do |f| %>
<div>
<%= f.label "What's the gist?" %><br>
<%= f.text_field :title %>
</div>
<div>
<%= f.label "Give us a plot" %><br>
<%= f.text_area :story %>
</div>
<%= f.submit "tell the truth" %>
<% end %>

app/views/plots/edit.html.erb
<ul><%  @plot.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<%= render "form" %>

app/views/plots/index.html.erb
<p style= "color:yellow;"><%= flash[:notice] %></p>
<h1>What happens next?</h1>
<h2>Matrix theories...</h2>
<%= link_to "take the red pill", new_plot_url, class: "redpill" %>
<% @plots.each do |p| %>
  <ul>
    <li>Transcript... <%= link_to p.title, plot_url(p.id) %></li>
  </ul>
<% end %>

app/views/plots/new.html.erb
<ul><%  @plot.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<%= render "form" %>

app/views/plots/show.html.erb
<h1><%= @plot.title %></h1>
<h2><%= @plot.story %></h2>
<%= link_to "back", plots_url %> | 
<%= link_to "edit", edit_plot_url %> | 
<%= link_to "delete", plot_url, :confirm => 'You are the one', :method => :delete %>
<%= link_to "take the red pill", new_plot_url, class: "redpill" %>